Withdraw function with IERC20 Dispatcher transfer
Token-Giver/token-giver-contracts pull request #21
Opened 2024-11-26 15:43 UTC by Pvsaint

feat: implemented and tested withdrawal function, implemented ERC20 token transfer and interface

2024-11-26 16:36 UTC, Pvsaint commented
I closed the previous PR and opened a new one

2024-11-26 17:29 UTC, mubarak23 commented
> I closed the previous PR and opened a new one

both build and test need to pass, at the moment they are all failing

2024-11-26 23:15 UTC, Pvsaint commented
Fixed

2024-11-27 00:14 UTC, Pvsaint commented
Everything should work fine now sir!

2024-11-27 13:02 UTC, mubarak23 requested changes
Also write unit test for the function

2024-11-27 13:02 UTC, mubarak23 commented on src/campaign.cairo
> +            self.withdrawal_balance.write(campaign_address, available_balance - amount);
this should go after transfer, only run this when the transaction , 

check to ensure the transfer was successful via ASSERTION, once it is true,

`self.withdrawal_balance.write(campaign_address, available_balance - amount);`

2024-11-27 18:32 UTC, closed without merging