feat: upgradability
Token-Giver/token-giver-contracts pull request #44
Opened 2024-12-12 22:51 UTC by Akshola00

implement and test upgrade using oz

2024-12-12 22:52 UTC, Akshola00 commented
@mubarak23 pls review

2024-12-14 19:15 UTC, mubarak23 requested changes

2024-12-14 19:15 UTC, mubarak23 commented on tests/test_campaign.cairo
> +fn test_upgradability() {
move this test to last section of the test file

2024-12-14 19:15 UTC, mubarak23 commented on tests/test_campaign.cairo
> +
add a test case that panic if wrong owner try to upgrade the contract

2024-12-15 20:01 UTC, Akshola00 commented
@mubarak23 pls review

2024-12-16 19:32 UTC, Akshola00 commented
@mubarak23 pushed the requested test

2024-12-17 09:00 UTC, merged